### ISSUE TITLE
prompt for password

### ISSUE THREAD

**Issue by dmd** [harvard-nrg/yaxil#10]
https://github.com/harvard-nrg/yaxil/blob/7980fa1f9dfcd45f85c7e8bfae0a8e7c19f1e5c3/scripts/ArcGet.py#L195

It would be nice if the password could be prompted for, in case someone doesn't want to -- or is forbidden by policy to - store their password in a file.

**Comment by dmd** [comment]
I tried to write  a PR for this, implementing a class that calls `getpass` if `--password` is not given, but got stuck because it seems you're doing your own post-argparse checking in `__init__.py` and I didn't want to start getting into the weeds.

**Comment by dmd** [comment]
I wrote a wrapper as a workaround:

```
#!/bin/bash
#
# 2021 ddrucker

set -o errexit

if [[ $# -eq 0 ]]; then ArcGet.py; fi

export XNAT_HOST=https://my-xnat-host
read -p "XNAT username [hit enter for $USER]: " XNAT_USER
read -s -p "XNAT password: " XNAT_PASS
export XNAT_PASS
export XNAT_USER=${XNAT_USER:-$USER}
ArcGet.py "$@"
```

**Comment by tokeefe** [comment]
I added functionality to prompt for a password in 44e720fe313cb45235d1dcad583057c28c4f20b1
