### ISSUE TITLE
confusing examples in documentation

### ISSUE THREAD

**Issue by dmd** [harvard-nrg/yaxil#17]
It's unclear to me if snippets in https://yaxil.readthedocs.io/en/latest/api.html aren't in the test suite, or if it's being tested against some other version, or what, because it appears to contain things that don't exist.

E.g., the example under `yaxil.scans` refers instead to `yaxil.scans2`. Same '2' after `extendedboldqc2`.

The example for `yaxil.experiments` refers instead to `yaxil.experiment`. 

I'm sure there's more...

**Comment by tokeefe** [comment]
I ran doctest before pushing out v0.7.3
