### ISSUE TITLE
AttributeError: 'module' object has no attribute 'XnatAuth'

### ISSUE THREAD

**Issue by jackgray** [harvard-nrg/yaxil#2]
Error when running example script in both 2.7 and 3.7.5 (with my own auth):

```
import os
import yaxil

auth = yaxil.XnatAuth(url='https://xnatastic.org', username='you', password='*****')

with yaxil.session(auth) as sess:
  # get all subjects for given project
  for subject in sess.subjects(project='PROJECT'):
    # get all MRIs for the given subject
    for experiment in sess.experiments(subject=subject):
      # get all scans for the given experiment
      for scan in sess.scans(experiment=experiment):
        # download scans with note 'REST1', 'REST2', or 'ANAT1'
        if scan['note'] in ('REST1', 'REST2', 'ANAT1'):
          sid = scan['id']
          outdir = os.path.join(subject.label, experiment.label, sid)
          sess.download(experiment.label, [sid], out_dir=outdir)
```

**Comment by tokeefe** [comment]
Did you install with `pip install`, `pip install --user`, `pipenv`, `pyenv`, `virtualenv`, or anything like that? I just tried a handful of methods (including Python 3.7.5 installed via `pyenv`) and could not replicate this error.

**Comment by jackgray** [comment]
> Did you install with `pip install`, `pip install --user`, `pipenv`, `pyenv`, `virtualenv`, or anything like that? I just tried a handful of methods (including Python 3.7.5 installed via `pyenv`) and could not replicate this error.

I installed with pip and pip3, and am getting the same error for python 2.7.1 and 3.7.5.
I also added `#!/usr/bin/env python3 ` without affect.
