### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by kristinarapuano** [harvard-nrg/yaxil#3]
atomic_write() in /commons/__init__.py returns an error when trying to decode characters that python already interprets as a string (line 74):

```
AttributeError: 'str' object has no attribute 'decode'
```

For reference, I'm using Python3 and the most up-to-date version of yaxil.

**Comment by tokeefe** [comment]
I was able to reproduce and patch this. There was a "decode" where there should have been an "encode". Try upgrading to the latest version 0.3.0 and let me know if that solves the issue.
